stages:
  - deploy
  - test
  - sync

.ssh_config_and_build: &standard_operation
  image: node:alpine3.16
  artifacts:
    paths:
      - build/*
    expire_in: 1 week
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$MAN_SERVER_SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

sync-openapi:
  <<: *standard_operation
  stage: test
  script:
    - apk add --no-cache git
    - git clone https://github.com/twcc/openapidoc.git
    - git clone https://${SEAN_USERNAME}:${SEAN_ACCESS_TOKEN}@git.twcc.ai/twcc/manual.git
    - cd manual
    - git checkout docusaurus-dev
    - export TZ=Asia/Taipei
    - export VERSION=`date +"openapi-sync-%Y%m%d_%H%M"`
    - git checkout -b $VERSION
    - cp -r ../openapidoc/Main/yaml/. ./openapi
    - npm install --legacy-peer-deps
    - npm run clear-api
    - npm run gen-api
    - git config --global user.email "sean.chang@twsc.io"
    - git config --global user.name "sean.chang@twsc.io"
    - git add .
    - git commit -m $VERSION
    - git push -u origin $VERSION
  when: manual

.build_template: &build_base
  <<: *standard_operation
  before_script:
    - npm install --legacy-peer-deps
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

test-build:
  <<: *build_base
  stage: test
  script:
    - npm run staging
  only:
    - merge_requests

deploy-staging:
  <<: *build_base
  stage: deploy
  script:
    - npm run staging
    - rsync -ravz --exclude en --delete build/ ubuntu@man.twcc.vip:/var/www/staging/
  only:
    - merge_requests
    - docusaurus-dev
  when: manual

deploy-staging-en:
  <<: *build_base
  stage: deploy
  script:
    - npm run staging
    - rsync -ravz --exclude "zh-Hant" --delete build/ ubuntu@man.twcc.vip:/var/www/staging/en/
  only:
    - merge_requests
    - docusaurus-dev-en
  when: manual

deploy-preview:
  <<: *build_base
  stage: deploy
  script:
    - npm run preview
    - rsync -ravz --exclude en --delete build/ ubuntu@man.twcc.vip:/var/www/preview/
  only:
    - docusaurus-dev
  when: manual

deploy-preview-en:
  <<: *build_base
  stage: deploy
  script:
    - npm run preview
    - rsync -ravz --exclude "zh-Hant" --delete build/ ubuntu@man.twcc.vip:/var/www/preview/en/
  only:
    - docusaurus-dev-en
  when: manual

deploy-production:
  <<: *build_base
  stage: production
  script:
    - npm run production
    - ls -alh build
    - rsync -ravz --exclude en --delete build/ ubuntu@man.twcc.vip:/var/www/production/
  only:
    - docusaurus-master
  when: manual

deploy-production-en:
  <<: *build_base
  stage: production
  script:
    - npm run production
    - ls -alh build
    - rsync -ravz --exclude "zh-Hant" --delete build/ ubuntu@man.twcc.vip:/var/www/production/en
  only:
    - docusaurus-master-en
  when: manual


send-to-GitHub:
  image: alpine
  stage: sync
  script:
    - apk update && apk add github-cli && apk add git
    - export GH_TOKEN=$GITHUB_APIKEY
    - git remote add github https://$GITHUB_USRERNAME:$GITHUB_APIKEY@github.com/twcc/man-vip
    - git fetch --unshallow github
    - git config --global user.email "August.Chao@twsc.io"
    - git config --global user.name $GITHUB_USRERNAME
    - git merge -s ours github/main --no-commit --no-ff --allow-unrelated-histories
    - git checkout -b $CI_COMMIT_SHORT_SHA
    - git push -u github $CI_COMMIT_SHORT_SHA
    - gh pr create --title "v$CI_COMMIT_SHORT_SHA" --body "Release TWCC manual"
    - gh pr create --base tws-sync --title "v$CI_COMMIT_SHORT_SHA" --body "Release TWCC manual"
    - gh release create "v$CI_COMMIT_SHORT_SHA" --title "v$CI_COMMIT_SHORT_SHA"
  only:
    - docusaurus-master
    - docusaurus-master-en
  when: manual

sync-from-GitHub:
  image: python:3.9
  stage: sync
  script:
    - git remote add github https://${GITHUB_USRERNAME}:${GITHUB_APIKEY}@github.com/twcc/man-vip
    - git remote add gitAug https://${AUG_USERNAME}:${AUG_ACCESS_TOKEN}@git.twcc.ai/twcc/manual.git
    - git fetch --unshallow github
    - git checkout github/tws-sync
    - export TZ=Asia/Taipei
    - export VERSION=`date +"Github-%Y%m%d_%Hhrs"`
    - git checkout -b $VERSION
    - git push -u gitAug $VERSION
  only:
    - merge_requests
  when: manual
