stages:
  - build
  - deploy
  - test

.ssh_config_and_build: &standard_operation
  image: node:alpine3.16
  stage: build
  artifacts:
    paths:
      - build/*
    expire_in: 1 week
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$MAN_SERVER_SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - npm install
    - npm run build
    - ls -alh build


building-staging:
  <<: *standard_operation
  script:
    - rsync -ravz --delete build/ ubuntu@man.twcc.vip:/var/www/staging/
  only:
    - merge_requests

building-preview:
  <<: *standard_operation
  stage: test
  script:
    - rsync -ravz --delete build/ ubuntu@man.twcc.vip:/var/www/preview/
  only:
    - docusaurus-dev

building-production:
  <<: *standard_operation
  stage: deploy
  script:
    - rsync -ravz --delete build/ ubuntu@man.twcc.vip:/var/www/production/
  only:
    - docusaurus-master
  when: manual

send-GitHub:
  image: ubuntu:latest
  stage: test
  script:
    - git clone https://$GITHUB_USRERNAME:$GITHUB_APIKEY@github.com/twcc/man-vip
    - cd man-vip
    - git remote add upstream $CI_REPOSITORY_URL
    - git fetch upstream
    - git config --global user.email "August.Chao@twsc.io"
    - git config --global user.name $GITHUB_USRERNAME
    - git merge -X upstream/$CI_COMMIT_REF_NAME --no-commit --no-ff --allow-unrelated-histories
    - git checkout -b $CI_COMMIT_SHORT_SHA
    - git commit . -m "-- Release $CI_COMMIT_SHORT_SHA --"
    - git push --set-upstream origin $CI_COMMIT_SHORT_SHA
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
    - apt update && apt install -y software-properties-common
    - apt-add-repository https://cli.github.com/packages
    - apt update && apt install -y gh
    - export GITHUB_TOKEN=$GITHUB_APIKEY
    - /usr/bin/gh pr create --title "v$CI_COMMIT_SHORT_SHA" --body-file /tmp/release_note_tmp
    - /usr/bin/gh release create "$CI_COMMIT_SHORT_SHA" --title "v$CI_COMMIT_SHORT_SHA"
  only:
    - docusaurus
  when: manual
