stages:
  - deploy
  - test
  - sync

cache: &global_cache
  key:
    files:
      - package.json
  paths:
    - node_modules/

.ssh_config_and_build: &standard_operation
  image: node:18-alpine3.16
  artifacts:
    paths:
      - ./*/build/*
    expire_in: 1 week
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$MAN_SERVER_SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  cache:
    <<: *global_cache

sync-openapi:
  image: node:18-alpine3.16
  stage: sync
  script:
    - apk add --no-cache git
    - git remote add gitSean https://${SEAN_USERNAME}:${SEAN_ACCESS_TOKEN}@git.twcc.ai/twcc/manual.git
    - cd ../
    - git clone https://github.com/twcc/openapidoc.git
    - cp -r ./openapidoc/Main/yaml/. ./manual/doc-zh/openapi
    - cp -r ./openapidoc/Main/yaml/. ./manual/doc-en/openapi
    - export TZ=Asia/Taipei
    - export VERSION=`date +"openapi-sync-%Y%m%d_%H%M"`
    - git checkout -b $VERSION
    - cd manual/doc-zh/
    - npm install --legacy-peer-deps
    - npm run clear-api
    - npm run gen-api
    - cd ../doc-en/
    - npm install --legacy-peer-deps
    - npm run clear-api
    - npm run gen-api
    - git config --global user.email "sean.chang@twsc.io"
    - git config --global user.name "sean.chang@twsc.io"
    - git add .
    - git commit -m $VERSION
    - git push -u gitSean $VERSION
  cache:
    <<: *global_cache
  when: manual

test-build:
  <<: *standard_operation
  stage: test
  script:
    - cd doc-zh
    - npm install --legacy-peer-deps
    - npm run staging
  cache:
    <<: *global_cache
  only:
    - merge_requests

deploy-staging:
  <<: *standard_operation
  stage: deploy
  script:
    - cd doc-zh
    - npm install --legacy-peer-deps
    - npm run staging
    - rsync -ravz --exclude en --delete build/ ubuntu@man.twcc.vip:/var/www/ramdisk/staging/
  only:
    - merge_requests
    - 427-change-cd-flow-to-ramdisk
  when: manual

deploy-staging-en:
  <<: *standard_operation
  stage: deploy
  script:
    - cd doc-en
    - npm install --legacy-peer-deps
    - npm run staging -- --locale en
    - rsync -ravz --exclude "zh-Hant" --delete build/ ubuntu@man.twcc.vip:/var/www/ramdisk/staging/en/
  only:
    - merge_requests
    - 427-change-cd-flow-to-ramdisk
  when: manual

deploy-preview:
  <<: *standard_operation
  stage: deploy
  script:
    - cd doc-zh
    - npm install --legacy-peer-deps
    - npm run preview
    - rsync -ravz --exclude en --delete build/ ubuntu@man.twcc.vip:/var/www/ramdisk/preview/
  only:
    - docusaurus-dev
  when: manual

deploy-preview-en:
  <<: *standard_operation
  stage: deploy
  script:
    - cd doc-en
    - npm install --legacy-peer-deps
    - npm run preview -- --locale en
    - rsync -ravz --exclude "zh-Hant" --delete build/ ubuntu@man.twcc.vip:/var/www/ramdisk/preview/en/
  only:
    - docusaurus-dev
  when: manual

deploy-production:
  <<: *standard_operation
  stage: deploy
  script:
    - cd doc-zh
    - npm install --legacy-peer-deps
    - npm run production
    - ls -alh build
    - rsync -ravz --exclude en --delete build/ ubuntu@man.twcc.vip:/var/www/ramdisk/production/
  only:
    - docusaurus-master
  when: manual

deploy-production-en:
  <<: *standard_operation
  stage: deploy
  script:
    - cd doc-en
    - npm install --legacy-peer-deps
    - npm run production -- --locale en
    - ls -alh build
    - rsync -ravz --exclude "zh-Hant" --delete build/ ubuntu@man.twcc.vip:/var/www/ramdisk/production/en
  only:
    - docusaurus-master
  when: manual


send-to-GitHub:
  image: alpine:3.16
  stage: sync
  script:
    - apk update && apk add github-cli && apk add git
    - export GH_TOKEN=$GITHUB_APIKEY
    - git remote add github https://$GITHUB_USRERNAME:$GITHUB_APIKEY@github.com/twcc/man-vip
    - git fetch --unshallow github
    - git config --global user.email "August.Chao@twsc.io"
    - git config --global user.name $GITHUB_USRERNAME
    - git merge -s ours github/main --no-commit --no-ff --allow-unrelated-histories
    - git checkout -b $CI_COMMIT_SHORT_SHA
    - git push -u github $CI_COMMIT_SHORT_SHA
    - gh pr create --title "v$CI_COMMIT_SHORT_SHA" --body "Release TWCC manual"
    - gh pr create --base tws-sync --title "v$CI_COMMIT_SHORT_SHA" --body "Release TWCC manual"
    - gh release create "v$CI_COMMIT_SHORT_SHA" --title "v$CI_COMMIT_SHORT_SHA"
  only:
    - docusaurus-master
  when: manual

sync-from-GitHub:
  image: python:3.9
  stage: sync
  script:
    - git remote add github https://${GITHUB_USRERNAME}:${GITHUB_APIKEY}@github.com/twcc/man-vip
    - git remote add gitAug https://${AUG_USERNAME}:${AUG_ACCESS_TOKEN}@git.twcc.ai/twcc/manual.git
    - git fetch --unshallow github
    - git checkout github/tws-sync
    - export TZ=Asia/Taipei
    - export VERSION=`date +"Github-%Y%m%d_%Hhrs"`
    - git checkout -b $VERSION
    - git push -u gitAug $VERSION
  only:
    - merge_requests
  when: manual

sync-to-nchc:
  image: python:3.9
  stage: deploy
  script:
    - cd syncer/
    - pip install -r requirements.txt
    - python do-sync.py -tws  ../doc-zh/
    - python do-sync.py -tws  ../doc-en/
  only:
    - merge_requests
  when: manual