/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'introduction',
    {
      type:'category',
      label: 'Quick Start',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting_start'}]
    },
    {
      type:'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
      },
      items: [{type: 'autogenerated', dirName: 'guide'}]
    },
  ],
  api: [
    'api',
    {
      type: 'autogenerated',
      dirName: 'api'
    }
  ],
  faq: [
    'faq',
    {
      type: 'autogenerated',
      dirName: 'faq'
    }
  ],
  ccs: [
    { type: 'autogenerated', dirName: 'ccs' }
  ],
  ccs_scheduled: [
    { type: 'autogenerated', dirName: 'ccs_scheduled' }
  ],
  vcs: [
    { type: 'autogenerated', dirName: 'ccs' }
  ],
  cos: [
    { type: 'autogenerated', dirName: 'cos' }
  ],
  member: [
    { type: 'autogenerated', dirName: 'member' }
  ],
  role_permission: [
    { type: 'autogenerated', dirName: 'role_permission' }
  ],
  hfs: [
    { type: 'autogenerated', dirName: 'hfs' }
  ],
  ccs_framwork_image: [
    { type: 'autogenerated', dirName: 'ccs_framwork_image' }
  ]
};

module.exports = sidebars;
