.ssh_config_default: &standard_ssh_operation
  image: node:alpine3.16
  stage: build
  artifacts:
    paths:
      - build/*
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$MAN_SERVER_SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


building-staging:
  <<: *standard_ssh_operation
  script:
    #- npm install
    #- npm run build
    #- ls -alh build
    #- rsync -ravz --delete build/ ubuntu@man.twcc.vip:./staging/
    - cat ~/.ssh/id_dsa
    - rsync -ravz --delete README.md ubuntu@man.twcc.vip:./staging/
  only:
    - docusaurus

