---
- hosts: localhost
  become: yes
  tasks:
    - name: install packages
      yum:
        name:
          - yum-utils
        state: latest
        update_cache: true
    - name: install Docker Repo
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
    - name: start docker
      systemd:
        name: docker
        state: started
    - name: install docker-compose
      shell: pip install docker-compose
     
    - name: enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
   

    

